### ISSUE TITLE
What is the meaning of PhoenixHeaderVer, EndofPhoenixHeader

### ISSUE THREAD

**Issue by PalgunaGopireddy** [SENSE-Lab-OSU/mstar_data_aug#4]
What is the meaning of `PhoenixHeaderVer` and `EndofPhoenixHeader` used in `mstar_data_aug/model/MSTAR_LOAD_IMAGE.m`

**Comment by nithin-pi** [comment]
Each mstar image consists the imaging geometry information stored in the header. This check is done to find the length of the header information. The header length is used as the index for finding the location of the image data in the file.
